use test
create table Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name varchar(255), Number_Needed int)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Vajrada Amethyst Sliver',1)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Vajrada Amethyst Fragment',9)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Vajrada Amethyst Chunk',9)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Vajrada Amethyst Gemstone',6)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Teachings of Light',9)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Guide to Light',63)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Philosophies of Light',114)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Old Handguard',36)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Kageuchi Handguard',96)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Famed Handguard',129)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Amakumo Fruit',168)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Storm Beads',46)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Molten Moment',18)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Mora',7050900)
insert into Raiden_Shogun_Inazuma_Polearm_Materials (Material_Name, Number_Needed) values ('Crown of Insight',3)